default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>

development:
  <<: *default
  database: jargon_development

test:
  <<: *default
  database: jargon_test

production:
  <<: *default
  database: jargon_production
